import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "@/app/sass/main.scss";
import Header from "@/app/components/header/Header";

const spaceMono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>
        <div className="container">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
